# SSD Performance Characterization Experiment Configuration
experiment_name: "ssd_performance_analysis"
device: "/dev/nvme0n1"  # WARNING: This will be overwritten!
test_file: "/mnt/testfile"  # Alternative to raw device

# Experiment parameters
runtime: 30        # seconds per test
ramp_time: 5       # seconds ramp time
iterations: 3      # repetitions per test

# Queue depth sweep configuration
qd_sweep:
  start: 1
  end: 256
  points: [1, 2, 4, 8, 16, 32, 64, 128, 256]
  mid_point: 8

# Block sizes to test
block_sizes: ["4k", "16k", "32k", "64k", "128k", "256k", "512k", "1m"]

# Read/write mixes
rw_mixes:
  - name: "100r0w"
    read: 100
    write: 0
  - name: "70r30w"
    read: 70
    write: 30
  - name: "50r50w"
    read: 50
    write: 50
  - name: "0r100w"
    read: 0
    write: 100

# System information (to be filled manually)
system_info:
  ssd_model: "Samsung 970 EVO Plus"
  interface: "PCIe 3.0 x4"
  capacity: "1TB"
  cpu: "Intel Core i7-10700K"
  os: "Windows 10"
  filesystem: "ext4"